test

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -24,8 +24,7 @@ jobs:
 
       - name: Run ktlint and report with reviewdog
         run: |
-          ktlint --reporter=checkstyle,output=ktlint-report.xml || exit 1
-        continue-on-error: true
+          ktlint --reporter=checkstyle,output=ktlint-report.xml || echo "style error"
 
       - name: Run reviewdog
         run: |
