mod issue 12

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -9,9 +9,20 @@ jobs:
   ktlint:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - run: |
-          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.44.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
-      - name: run ktlint
+      - uses: actions/checkout@v2
+
+      - name: Install ktlint
         run: |
-          ktlint --reporter=checkstyle,output=build/ktlint-report.xml
+          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.44.0/ktlint
+          chmod a+x ktlint
+          sudo mv ktlint /usr/local/bin/
+
+      - name: Run ktlint
+        run: |
+          ktlint --reporter=checkstyle,output=build/ktlint-report.xml || echo "Ktlint check failed."
+
+      - name: Upload Ktlint report
+        uses: actions/upload-artifact@v2
+        with:
+          name: ktlint-report
+          path: build/ktlint-report.xml
