mod issue 12

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -8,8 +8,10 @@ on:
 jobs:
   ktlint:
     runs-on: ubuntu-latest
+
     steps:
-      - uses: actions/checkout@v2
+      - name: Checkout code
+        uses: actions/checkout@v2
 
       - name: Install ktlint
         run: |
@@ -17,12 +19,13 @@ jobs:
           chmod a+x ktlint
           sudo mv ktlint /usr/local/bin/
 
-      - name: Run ktlint
+      - name: Run ktlint and report with reviewdog
         run: |
-          ktlint --reporter=checkstyle,output=build/ktlint-report.xml || echo "Ktlint check failed."
+          ktlint --reporter=checkstyle,output=ktlint-report.xml || echo "Ktlint check failed."
+          reviewdog -f=checkstyle -name="ktlint" -reporter=github-pr-review -level=error < ktlint-report.xml
 
       - name: Upload Ktlint report
         uses: actions/upload-artifact@v2
         with:
           name: ktlint-report
-          path: build/ktlint-report.xml
+          path: ktlint-report.xml
